language: java
sudo: false
jdk: openjdk8
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2789fa0cc6521142fbb2
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  - secure: E9jjRhYcBpYZz5gq0XTTOhrHPw+HrdSsyhrOws/Wh6bfnxR/zAVTtbIsZPIKY6Rq9iSnyVW/ZnwQ8wVAU+OR+XqiCVUMrPcKzfRu2dn9dFz+GuQ9zj6i+ssg5sTPQ9Gx8XPjiEsOtmidwnGPoLIseucjkzMvL8E5Gt6x4r6/Y1I=
  - secure: IlWfX1oy1TClrfjh9izV17H2GWrx7DPGmy1h7a1JFzSCCrQ5zYM4JSzOsQh8vis8Axrk7YXmKmyBODYYMw1lj0hBT5wMWDEWHNWW5LRwOlSzjnEFnGLJjo2bqi5UY+eNzI/RDWxgeKiFQuuTQViLJ3b6l6kahNyiIvDFjMy1Vjk=
  - secure: VWKQYjuMV9e6d6tygYYoXM6X40m56cHfSdXR8Unp2pEf3+7iU0ByQC4vAAyU9RueDOKSpUxnav/t1/FCHIV5u7Tg1erpsXYGGtKd3j0JM4HUw6V2xrGRSCF3od+GF4KnnmVXgX2iO6OZ0PaGmkXxi7mO0c4j2YOveqC3+0RLhEs=
  - secure: GZMYy7inMckWc4XD2ABKv0diC04rEoRNlCxe3uMXXpOAOCNpDqGdtWADs/+nHU0J/Suv4+M5rWDw6a6GWNej6to2E8q7+hz6rIbmqcnVhPxjpzncgabM23mbRNREY5rRWmPdJbC8GFqLWtI6keR7VR1ArtNU1uuPZ1YDMZ3Eh0g=
  - secure: O0pZxxmi0xwMexmOLBNsROvcynf/KemdIwHtOnAW4BmpqZ7pcjrsXxClLMKHCLX7mHXmfZ58Gj13glvF93kwgDbQSjHpnNF+LnjxvMLoOz9ezroiWT4J3q7YSK2i42r2GFTXTyCz8PkPI9ZxOSmzhoOSpJ6znZhnrpEs9+PUems=
  - secure: ESFeDqKPYr5wzrr7ylO7Vt7eZOpOOTaWlxksBoETSha48SA/dyu55an6rKIgoebHic/m9vPUWi66VkfqWFyD4y2ag/s3FTCwiZDoLhIX29pzBnmg613Fml+mJliIe1KxgrGOgRWXtF6Ype37FONkAZQUXSUVbEY7AFUymtZc4TU=
